### ISSUE TITLE
[Implementation] Implement suite provided by support tools team

### ISSUE THREAD

**Issue by captios** [cmsc22000-project-2018/redis-tries#33]
Synthesizing a suite of visualization functions provided by the support-tools team with our current trie implementation.

**Comment by valeriehan6** [comment]
Taking over this issue now since no work has been done on it.

**Comment by valeriehan6** [comment]
Asking support_tools team for clarification on their functions.

**Comment by captios** [comment]
05/20/18
Naive implementation into Makefile done in commit 84d0e6f464969dd79f5bd049464985614d7979aa. Make bugs fixed in commit 628c03cf69e20398676e335758f398e082854a47.
Testing algorithms remains to be done bc of difficulty of testing visualization functions.

**Comment by captios** [comment]
05/21/18
Commits 9092462c123202526ab7fe94463ee2d441443e46 and 7634902eab4c33f6dcfef050e4d36ea342b95554 made the viz_algorithms suite ready for integration. Tests, however, and some compiler warnings, however, are unaddressed.

**Comment by DustinoZhang** [comment]
What's the status on this/when should we expect this to be finished? @captios @valeriehan6

**Comment by captios** [comment]
@DustinoZhang Immediate implementation is done, but I haven't written tests for them because I'm not sure how to write them for visualization functions atm.

**Comment by valeriehan6** [comment]
https://github.com/cmsc22000-project-2018/redis-tries/tree/valerie/visualization

**Comment by valeriehan6** [comment]
Removing Adela since she created her own issue.
