### ISSUE TITLE
Create first draft of design document

### ISSUE THREAD

**Issue by mpcsh** [cmsc22000-project-2018/redis-tries#5]
The design doc will live in the GitHub wiki - you can find the Wiki button above this issue. @dengyijia and @valeriehan6 are responsible for the first draft of the first draft; one of you should comment below when you're ready for everyone to contribute.

**Comment by valeriehan6** [comment]
Here's the [design doc](https://docs.google.com/document/d/1-ME01Njtdw3DbCLGY1A8OccEamQi1_bA3bdZ8jdXXBA/edit?usp=sharing).

**Comment by valeriehan6** [comment]
typedef struct trie_t trie_t;
trie_t {
	char current; // The first node_t will be ‘/0.’
	trie_t *children[ALPHABET_SIZE];
	int EOW; // if EOW is 1, reached end of a word
}

ALPHABET_SIZE = 256;
- “We should be able to take in any string” -Mark
- Worry about optimizing late0r

new_trie_t();
- Allocates memory for new trie_t 
- Sets current to be ‘/0’
- All children are initialized to NULL
- EOW set to 0

add_node(char current, trie_t *t);
- Creates new node in t
- Set t->children[current] to be current
- All other children are set to NULL
- EOW set to 0?

int contains_string(char* word, trie_t *t);
- Checks t for word
- For each trie node
    - Check if entry of the next character exists in the children array
    - If so, move into that node in the array until there are no more characters (except the null character)
- Check if EOW is 1 in that node
- Returns 1 if word is in t and 0 if not

int insert_string(char *word, trie_t *t); 
- Inserts word into trie
- Check if word is in trie with contains_string
- For each trie
    - Check if entry of the next character exists in the children array
    - If so, move into that node in the array
    - If not, add a new node
    - Then move on to the next character in string
- Set the EOW of the last node to 1

int delete_string(char *word, trie_t *t ); 
- Delete word in t
- Check if word is in t with contains_string
- Checks if word is prefix to other words
- Checks if word has prefix to other words

void free_trie(trie_t *t);
- Frees t and its children recursively

**Comment by DustinoZhang** [comment]
I can't access the document. I've requested access to it- could you approve it?

**Comment by DustinoZhang** [comment]
https://github.com/cmsc22000-project-2018/redis-tries/wiki/Design-Document-v1

I edited Adela and Valerie's rough draft and put it into this wiki page just for grading reference.
